### ISSUE TITLE
Incorrect module name

### ISSUE THREAD

**Issue by manoelcampos** [SaiWebApps/RandomWordGenerator#2]
At the provided example in the README, isn't it `from randomwordgenerator import randomwordgenerator` instead of `from randomgenerator import randomwordgenerator`?

The example raises the error `ModuleNotFoundError: No module named 'randomgenerator'`.

I'm using version 1.0.0 with python 3. The following example works fine:

```python
from randomwordgenerator import randomwordgenerator

num_words = 20
words = randomwordgenerator.generate_random_words(num_words)
print(words)
```

**Comment by khodjabekova** [comment]
try
pip install randomwordgenerator

**Comment by laurenwalker** [comment]
Thanks for creating this issue, I found this module today and have been banging my head against the wall figuring out what was wrong.
